# Generated by Django 2.0.5 on 2018-05-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maker',
            name='salary',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='maker',
            name='telephone',
            field=models.IntegerField(),
        ),
    ]
