# Generated by Django 2.0.5 on 2018-05-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_auto_20180515_0538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11)),
                ('size', models.CharField(choices=[('sm', 'small'), ('ch', 'Chields'), ('M', 'medium'), ('gr', 'Girl')], max_length=2)),
                ('machine', models.ManyToManyField(to='factory.Machine')),
            ],
        ),
        migrations.AddField(
            model_name='raw',
            name='color',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
