# Generated by Django 2.0.5 on 2018-05-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_auto_20180518_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='raw',
            name='machine',
            field=models.ManyToManyField(to='factory.Machine'),
        ),
        migrations.RemoveField(
            model_name='raw',
            name='raw',
        ),
        migrations.AddField(
            model_name='raw',
            name='raw',
            field=models.CharField(choices=[('A', 'alpha'), ('S', 'Asher Ramadan'), ('M', 'Masrien'), ('G', 'Gawada')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
